version: "3.3"
services:
  ultimateam-app:
    build: .
    image: ultimateama
    restart: on-failure
    ports:
      - 8080:3000
    container_name: ultimateam-app
    environment:
      - APP_PORT=3000
      - MONGO_DB_URL=mongo-db
      - MONGO_DB_PORT=27017
      - SLACK_WEBHOOK_URL=https://hooks.slack.com/services/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
    networks:
      - ultimateam-network
    volumes:
      - ./:/app:cached

  mongo-db:
    image: mvertes/alpine-mongo
    ports:
      - 27016:27017
    container_name: mongo-db
    networks:
      - ultimateam-network

networks:
  ultimateam-network:
    driver: bridge