# Tradepile not sold
TRADE_STATE_EXPIRED = 'expired'

# Tradepile sold
TRADE_STATUS_CLOSED = 'closed'

# Tradepile still active
TRADE_STATE_ACTIVE = 'active'

BID_STATE_HIGHEST = 'highest'
BID_STATE_OUTBID = 'outbid'

SELL_STRATEGY_SNIPER = 'sniper'
SELL_STRATEGY_G300 = 'gold300'

WATCHLIST_SIZE = 50
MAX_PAGE_FOR_SEARCH = 210
PILE_SIZE = 100

EA_TAX_PERCENTAGE = .95

# Strategies
GOLD300_STRATEGY = 'gold300'
SNIPER_STRATEGY = 'sniper'
EXCHANGE_STRATEGY = 'ex'


DEF_ID_SQUAD_FITNESS = 5002006
